# Generated by Django 6.0.3 on 2026-03-26 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('medication_type', models.CharField(choices=[('pill', 'Pill'), ('liquid', 'Liquid'), ('injection', 'Injection'), ('other', 'Other')], max_length=20)),
                ('dosage', models.CharField(max_length=50)),
                ('instructions', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('event_type', models.CharField(choices=[('lid_opened', 'Lid Opened'), ('button_pressed', 'Button Pressed'), ('dose_removed', 'Dose Removed')], max_length=30)),
                ('event_datetime', models.DateTimeField()),
                ('processed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_events', to=settings.AUTH_USER_MODEL)),
                ('medication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_events', to='medications.medication')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plan_type', models.CharField(choices=[('single', 'Single Medication'), ('alternating', 'Alternating Medications')], default='single', max_length=20)),
                ('dose_ml_primary', models.DecimalField(decimal_places=1, max_digits=4)),
                ('dose_ml_secondary', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('interval_hours', models.PositiveIntegerField()),
                ('start_datetime', models.DateTimeField()),
                ('reminder_enabled', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medication_primary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_treatment_plans', to='medications.medication')),
                ('medication_secondary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_treatment_plans', to='medications.medication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_sent', models.BooleanField(default=False)),
                ('overdue_alert_sent', models.BooleanField(default=False)),
                ('scheduled_datetime', models.DateTimeField()),
                ('confirmed_datetime', models.DateTimeField(blank=True, null=True)),
                ('scheduled_dose_ml', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('dose_ml_given', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('administered_by', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('taken', 'Taken'), ('missed', 'Missed')], default='pending', max_length=20)),
                ('confirmed_by', models.CharField(blank=True, choices=[('manual', 'Manual'), ('device', 'Device'), ('both', 'Both')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dose_logs', to=settings.AUTH_USER_MODEL)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dose_logs', to='medications.medication')),
                ('treatment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dose_logs', to='medications.treatmentplan')),
            ],
        ),
    ]
